CREATE Database DatabaseTask;

USE DatabaseTask;

CREATE TABLE department (
DNUM INT PRIMARY KEY,
DNAME NVARCHAR(70),
SSN CHAR(9),
MHDATE DATE,
);

ALTER TABLE department
ADD FOREIGN KEY (SSN) REFERENCES employee(SSN);

SELECT * FROM department;

CREATE TABLE employee (
SSN CHAR(9) PRIMARY KEY,
FNAME NVARCHAR(50),
LNAME NVARCHAR(50),
GENDER CHAR(1),
BIRTHDATE DATE,
SUPERSSN CHAR(9),
DNUM INT,
FOREIGN KEY (SUPERSSN) REFERENCES employee(SSN),
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);

SELECT * FROM employee

CREATE TABLE dependent (
Name NVARCHAR(50),
SSN CHAR(9),
GENDER CHAR(1),
BIRTHDATE DATE,
PRIMARY KEY (Name, SSN),
FOREIGN KEY (SSN) REFERENCES employee(SSN)
);

SELECT * FROM dependent

CREATE TABLE DEARTMENTLOC(
LOCATION NVARCHAR(50),
DNUM INT,
PRIMARY KEY (DNUM, LOCATION),
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);

SELECT * FROM DEARTMENTLOC

CREATE TABLE PROJECT(
PNUMBER INT PRIMARY KEY,
PNAME NVARCHAR(50),
LOCATION NVARCHAR(50),
CITY NVARCHAR(50),
DNUM INT,
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);

SELECT * FROM PROJECT

CREATE TABLE WORKON(
SSN CHAR(9),
PNUMBER INT,
WORKINGHOUR TIME,
FOREIGN KEY (SSN) REFERENCES employee(SSN),
FOREIGN KEY (PNUMBER) REFERENCES PROJECT(PNUMBER)
);

SELECT * FROM WORKON